### ISSUE TITLE
Trading Post trading volume increases during Beer Factory Boost and doesn't go back to normal afterwards

### ISSUE THREAD

**Issue by 2ndK16** [wol-soft/beerplop-issues#49]
During a Beer Factory Boost, the trading volumes of the Trading Posts is increased as well. If you manually set the trading volume to MAX in this time, it will stay on this level wven ater the Beer Facotry Boost is over, enabling you to trade disproportionately large amounts of goods.

**Comment by wol-soft** [comment]
Additionally the Beer Factory Boost currently doesn't increase the traded amount automatically.

**Comment by wol-soft** [comment]
Fixed with version 1.56.0. Now the traded amount is increased if a Beer Factory Boost begins and is decreased when the boost ends.

Also if the trading route is set to "Not automatically adjust the traded value" and the boost ends or the game is reloaded (required as the traded currently traded amount is persisted in the save state) the traded amount will be reset to the max. available amount.
