### ISSUE TITLE
Disable Autobuy

### ISSUE THREAD

**Issue by Marcnesium87** [wol-soft/beerplop-issues#58]
should Disable/Enable the Buttons inside every Building. So we can use it to Kick off all and then enable a speicific Building. 
So the Disable Button should control all Buttons in every Building.

**Comment by wol-soft** [comment]
This behaviour would force me to enable all auto buyers for each building after I disabled all buildings to save some plops (eg. for a bottle cap factory level up). I guess it's more an use case to have all available auto buyers enabled and then to pause/start all buyers with the global enable/disable switch.

If auto buyers shall be enabled only for some specific buildings manual configuration seems reasonable.

**Comment by Marcnesium87** [comment]
Then we need an Switch Building Arrow to fast switch between Buildings. For now I have to open Building Tab, switch Button, close and redo for all Buildings.

**Comment by wol-soft** [comment]
A fast switch button (or a menu to select the currently managed building) seems like a good idea, I think I'll create a new issue for this change, but it won't change the use case behind the disable/enable switch.

The requested change of the switch behaviour would still force the player to enable each building manually if he disabled the automation once.

As described in my previous comment disabling the switches for each building with the global switch to configure automation only for specific buildings seems not as the expected behaviour and the main use case of a global switch.

The global switch as a pause/start mechanic for the automation also aligns with the behaviour of other automation controls, eg. the global switch to enable/disable automatic cloning (#40)

**Comment by Marcnesium87** [comment]
Problem Solved
